fix: fixed issue where environment variable for cloudflare deployment is not found

diff --git a/.github/workflows/build-to-cloudflare-pages.yml b/.github/workflows/build-to-cloudflare-pages.yml
--- a/.github/workflows/build-to-cloudflare-pages.yml
+++ b/.github/workflows/build-to-cloudflare-pages.yml
@@ -1,12 +1,12 @@
 name: Build to Cloudflare Pages
 
 permissions:
-  actions: write
-  checks: write
-  contents: write
-  deployments: write
-  pull-requests: write
-  statuses: write
+    actions: write
+    checks: write
+    contents: write
+    deployments: write
+    pull-requests: write
+    statuses: write
 
 on:
     pull_request:
@@ -36,7 +36,7 @@ jobs:
               uses: actions/github-script@v3
               with:
                   script: |
-                      const preview_url = "https://" + "${{ github.head_ref }}" + ".deriv-com.pages.dev"
+                      const preview_url = "https://" + "${{ github.head_ref }}" + ".deriv-com-test-links.pages.dev"
                       const comment = [
                         '## Cloudflare Pages Preview link',
                         '| Name | Result |',
@@ -79,16 +79,33 @@ jobs:
             - name: Build project
               id: build-project
               run: npm run build
-            
+
             - name: Publish to Cloudflare Pages
-              uses: cloudflare/wrangler-action@2.0.0
-              
-              with:
-                apiToken: ${{ secrets.CLOUDFLARE_TEST_LINKS_API_TOKEN }}
-                accountId: ${{ secrets.CLOUDFLARE_TEST_LINKS_ACCOUNT_ID }}
-                command: pages publish public --project-name=deriv-com --branch=${GITHUB_REF_NAME}
-                         echo "preview_url=$(pages info --project-name=deriv-com --branch=${GITHUB_REF_NAME} --format preview_url)" >> $GITHUB_OUTPUT
-            
+              id: publish-to-pages
+              env:
+                  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_TEST_LINKS_API_TOKEN }}
+                  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_TEST_LINKS_ACCOUNT_ID }}
+              run: |
+                  echo "Installing Wrangler CLI"
+                  npm i -g wrangler
+
+                  echo "Deploying build to Cloudflare Pages"
+                  directory='public'
+                  projectName='deriv-com'
+                  branch=$GITHUB_HEAD_REF
+
+                  preview_url=$(wrangler pages deploy $directory --project-name=$projectName --branch=$branch > log.txt 2>&1; echo $?)
+                  echo "------"
+                  cat log.txt
+
+                  branchName=$(echo $branch | sed 's/[\/_]/-/g')
+                  if grep -q "Deployment complete" log.txt; then
+                    echo "preview_url=https://$branchName.deriv-com-test-links.pages.dev" > "$GITHUB_OUTPUT"
+                  else
+                    echo "Deployment to Cloudflare Pages failed."
+                    exit 1
+                  fi
+
             - name: Retrieve Cloudflare Pages Preview URL
               id: cloudflare_pages_preview_url
               uses: actions/github-script@v3
